version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development

  db:
    build:
      context: ./db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: student_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: