version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development

  db:
    build:
      context: ./db
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: student_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: