
services:
  db:
    build:
      context: ./db
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: student_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: ./app
    container_name: flask_app
    restart: always
    ports:
      - "5001:5000"
    depends_on:
      - db  # Ensures the 'db' service starts first
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000

volumes:
  mysql_data:
